Added feature#4: LocalStorage
tapascript/solid-bucket-list pull request #5
Opened 2023-11-11 17:26 UTC by Eth3R-One

Added feature to add new wish to local storage and get saved wishes from local storage.

2023-11-13 02:16 UTC, atapas commented on src/AddToBucket.jsx
> +    localStorage.setItem("solid-bucket-list", JSON.stringify(allWishes))
@Eth3R-One Let's create a utility file for the lcalstorage related operations... u can create a util folder under src and create the utility under that.

2023-11-13 08:00 UTC, Eth3R-One commented
Added new utility file for local storage related operations. added two functions to get and save wishes at this moment
src/
  |__util/
            |__localStorageUtility.js

2023-11-14 13:07 UTC, sarowarhosen03 commented
hello sir
i have done this can i make a pR

2023-11-14 14:34 UTC, Eth3R-One commented
@sarowarhosen03 Yes I've made the changes and waiting for review and approval.

2023-11-14 14:45 UTC, sarowarhosen03 commented
> @sarowarhosen03 Yes I've made the changes and waiting for review and approval.

Oh okay thanks for letting me know

2023-11-15 14:19 UTC, atapas commented
@Eth3R-One Could you please resolve the merge conflicts?

2023-11-15 16:28 UTC, Eth3R-One commented
@atapas Dada I resolved the conflicts. Let me know if there is any issue

2023-11-16 03:32 UTC, atapas requested changes

2023-11-16 03:32 UTC, atapas commented on src/util/localStorageUtil.js
> +  //   if (!wishes) return dummy_Data;
remove the commented lines

2023-11-16 04:11 UTC, atapas approved these changes

2023-11-16 04:12 UTC, merged

2023-11-16 04:40 UTC, atapas commented
@all-contributors please add @Eth3R-One  for code

2023-11-16 04:43 UTC, atapas commented
@all-contributors please add @atapas for Infrastructure